server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml # This location needs to be writeable by Promtail.

clients:
  - url: http://localhost:3100/loki/api/v1/push  # add loki deployed server IP to loacalhost

scrape_configs:
- job_name: name of your application
  static_configs:
  - targets:
      - localhost
    labels:
      job: Bunnings API
      host: 10.1.1.1 #your application IP address
      __path__: /your_application_path/log/*log
