server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml # This location needs to be writeable by Promtail.

clients:
  - url: http://localhost:3100/loki/api/v1/push  

scrape_configs:
- job_name: Bunnings-order-adapter
  static_configs:
  - targets:
      - localhost
    labels:
      job: Bunnings API
      host: 10.1.1.1 #your application IP address
      __path__: /home/oms/bunnings-adapter/log/*log
